### ISSUE TITLE
Issue with CAN Diagnostic Windows

### ISSUE THREAD

**Issue by longtranchau** [rbei-etas/busmaster#1008]
I have an issue with CAN Diagnostic Windows. It seems that Busmaster 3.x.x (both 3.0.0 and 3.1.0) can't handle multi-frame response from ECU. After ECU sent first frame, Busmaster didn't send flow control frame and the communication was cancelled.

![busmaster 3 0 0](https://cloud.githubusercontent.com/assets/8691192/20910031/146c3b56-bb9a-11e6-9a45-6d3d89e42d80.PNG)

If I use Busmaster 2.6.4, it's ok. Busmaster 2.6.4 can handle multi frame response from ECU.

![busmaster 2 6 0](https://cloud.githubusercontent.com/assets/8691192/20909988/c9f7d1a2-bb99-11e6-8d2a-e469303a31c5.PNG)

Regards,
Long Tran

**Comment by ddeussen** [comment]
I have basically reported the same issue https://github.com/rbei-etas/busmaster/issues/995 but have not received any feedback for 12 days now.

**Comment by wenluoma** [comment]
could you tell me where i can download BUSMASTER 2.6.4???

**Comment by RBEI-busmaster** [comment]
Fixed with v3.2.0. Please download and use the latest version
