### ISSUE TITLE
No Channel Configuration with IXXAT VCI and Busmaster 3.1.0

### ISSUE THREAD

**Issue by FAMOSTester** [rbei-etas/busmaster#1016]
Hello together,

actually i try the new version of Busmaster (3.1.0) and want to connect my IXXAT USB-to-CAN compact module (VCI 3.5.4.4543 / VCI 2.20.0.855). 
The driver can be selected and the module be started. But i can't configure the module. If i press the "Channel Configuration" button... nothing happens.
If i try the older version i can configure my module (baudrate etc.). The Vector Driver runs...
Any ideas?

**Comment by nostar** [comment]
See #1017 

This has been labelled a support issue, but is in fact a bug in 3.1.0.

**Comment by FAMOSTester** [comment]
Good to know. Then i will wait for an update. Thanks for the reply!

**Comment by RBEI-busmaster** [comment]
Duplicate to #1017. #1017 will be used for tracking. Hence, closing the issue.

**Comment by RBEI-busmaster** [comment]
@FAMOSTester,  We would like to get your support in testing the fix with IXXAT hardware. Could you please send your contact details to BUSMASTER@in.bosch.com.

**Comment by RBEI-busmaster** [comment]
Hi,
Please install the patch from the below location and let us know if it addresses your issue.
https://github.com/rbei-etas/busmaster-transient/blob/master/BUSMASTER_Patch_v3.1.0.exe 

Please write to busmaster@in.bsoch.com if any issues are found.
Based on the feedback, the patch will be made available as part of next version.
