### ISSUE TITLE
Message window column sorting broken

### ISSUE THREAD

**Issue by nostar** [rbei-etas/busmaster#1023]
The ability to sort a column in the message window while connected has always been broken, and now the ability to sort when disconnected is also broken.

**Comment by RBEI-busmaster** [comment]
Fixed with v3.2.0. Please download and use the latest version

**Comment by richClubb** [comment]
Sort works but the sorted messages are out of alignment. The entries in the window are sorted, but the corresponding objects do not get sorted. Therefore when you click on an item to check the signals you can end up getting the wrong signal list.
This is in 3.2.2
