### ISSUE TITLE
the function "Diagnostics" of the BUSMASTER 3.1.0 cannot send Flow Control Frame to the VCU

### ISSUE THREAD

**Issue by wenluoma** [rbei-etas/busmaster#1028]
i use the "Diagnostic" function of the BUSMASTER version 3.1.0, with the proper settings(eg. Interface:29 bits  Normal ISO; CAN ID of the Request to ECU and Response from ECU ), then i send a request frame with the Tester, ECU receive the request fram, and send the first frame to Tester, but the Tester could not send the flow control frame to the ECU, so could you help to explain this, or you can also tell me how to modify the source  code?? 
thanks!

wenluoma

**Comment by RBEI-busmaster** [comment]
This issue is same as #1008 . #1008 will be used for tracking.
