### ISSUE TITLE
whether it must to install the following 2 softwares before install the Busmaster?

### ISSUE THREAD

**Issue by Wenji2016Jim** [rbei-etas/busmaster#1029]
![busmaster download](https://cloud.githubusercontent.com/assets/23520856/21342315/4836004c-c6cc-11e6-9482-2c4e1a939ce5.PNG)

i want to install the Busmaster, whether it is necessary to install the up 2 softwares before it ?

**Comment by RBEI-busmaster** [comment]
VS2013 Redistributable will be installed by BusMaster v3.1.0 installation. MinGW component needs to be installed to use 'Node Simulation' feature.
