### ISSUE TITLE
errors when run with debug mode

### ISSUE THREAD

**Issue by wenluoma** [rbei-etas/busmaster#1031]
when i run with debug mode, it pops up a message window like the following: 
so please tell me the reason? i tried to change a big memory but it still have this problem.

![insufficient memory available](https://cloud.githubusercontent.com/assets/24406545/21477470/2b376c28-cb7d-11e6-8e48-66aa73c0d634.PNG)
![unhandled exception](https://cloud.githubusercontent.com/assets/24406545/21477471/2bd1f112-cb7d-11e6-8588-92814026a529.PNG)

**Comment by RBEI-busmaster** [comment]
Hi,
Please execute the build.bat located at \busmaster\Sources\ which builds in release mode and let us know if you are able to launch BUSMASTER.
We compiled the following solutions in the below order using Visual Studio 2013 in Debug mode and it worked fine without any issues.

1. busmaster\Sources\Kernel\BusmasterKernel.sln
2. busmaster\Sources\BUSMASTER\BUSMASTER.sln

**Comment by wenluoma** [comment]
Hello,

first, i tested the BUSMASTER souce code with release mode, although there is still some issues about the build enviroment, i can fix these problems and the BUSMASTER main interface could be launched,and the Diagnostics function seems without any problems. so it seems work well now.
then i try to use Diagnostics function with Debug mode. however. when i click "Diagnostics" --> "Settings", there is a error, please see the attach. is there anything i missed?

wenluo


________________________________________
发件人: RBEI-busmaster [notifications@github.com]
发送时间: 2017年1月3日 7:38
收件人: rbei-etas/busmaster
抄送: wenluoma; Author
主题: Re: [rbei-etas/busmaster] errors when run with debug mode (#1031)

Hi,
Please execute the build.bat located at \busmaster\Sources\ which builds in release mode and let us know if you are able to launch BUSMASTER.
We compiled the following solutions in the below order using Visual Studio 2013 in Debug mode and it worked fine without any issues.

  1.  busmaster\Sources\Kernel\BusmasterKernel.sln
  2.  busmaster\Sources\BUSMASTER\BUSMASTER.sln

―

**Comment by garnett33** [comment]
Hi, 

I tried to execute the build.bat as you proposed but it is still not working in both modes debug and release. 
Moreover, when I run it in debug mode, I have the same problem than wenluoma : "Insufficient Memory Available" message pops up. I think it could be a Visual Studio configuration issue so could you please tell me what parameters you set before you compile and run the project ? 

Thank you in advanced, 

Maxime

**Comment by RBEI-busmaster** [comment]
@Maxime, we are unable to reproduce the issue. Could you please send your contact details to Busmaster@in.bosch.com. We can discuss further.
