### ISSUE TITLE
BTR calculation error

### ISSUE THREAD

**Issue by PPSXIN** [rbei-etas/busmaster#1034]
On the preview version like v3.0.0, when the Baud Rate is set to 125000 bps, the BTR0 will be 0x47 and BRP will be 8, it's ok to work.
but on the version v3.1.0, if the Baud rate is set to 125000 bps, by default the BTR0 will be 0x41 and BRP will be 2, it can't be connected with CAN bus. If these parameters are changed manually as the preview version, it's ok.
v3.1.0 screen shoot:
![image](https://cloud.githubusercontent.com/assets/20082167/21668781/0429a8d8-d340-11e6-9820-d6b4283d0894.png)
v3.0.0 
![image](https://cloud.githubusercontent.com/assets/20082167/21668786/11ea48a6-d340-11e6-90f5-18f3b1a52464.png)

**Comment by RBEI-busmaster** [comment]
We would like to get your support in testing the fix. Could you please send your contact details to BUSMASTER@in.bosch.com.

**Comment by RBEI-busmaster** [comment]
Hi,
Please install the patch from the below location and let us know if it addresses your issue.
https://github.com/rbei-etas/busmaster-transient/blob/master/BUSMASTER_Patch_v3.1.0.exe

Please write to busmaster@in.bsoch.com if any issues are found.
Based on the feedback, the patch will be made available as part of next version.

**Comment by geier99** [comment]
Hi,
my BTR calculation issues are solved. ( for example I wasn't  able to set the baudrate to 33333 bps).

**Comment by RBEI-busmaster** [comment]
@geier99, Thanks for the feedback. Could please let us know the Operating System used.

**Comment by geier99** [comment]
Hi,
I have used: Windows 8.1 Pro   ( with PCAN-USB interface)
And today it solved also my issues on a Windows 7 Pro system.  ( with  PCAN-USB Pro interface)

**Comment by PPSXIN** [comment]
@RBEI-busmaster 
Hi,
Sorry for the late feedback.

The installation failed when I tried to install the patch file:
![screenshoot](https://cloud.githubusercontent.com/assets/20082167/22976285/1cb5c166-f3c5-11e6-8830-390ec50da0ca.png)

**Comment by PPSXIN** [comment]
BTW, the OS is win7 X64.

**Comment by RBEI-busmaster** [comment]
Fixed with v3.2.0. Please download and use the latest version
