### ISSUE TITLE
Signal watch configure cannot send list to signal watch window

### ISSUE THREAD

**Issue by connectpeoplewith** [rbei-etas/busmaster#1035]
OS: Win 10
GCC and VS 2013 redistribute installed
Busmaster 3.1.0

When I add the signal into signal watch window: after checking several signals and press OK, the signal watch window still is blank. Although when bus is on, the signals show in the watch window, it's better for us to know whether we add them successfully or not immediately. thanks. 

![image](https://cloud.githubusercontent.com/assets/24996066/21755230/4a7071aa-d5c5-11e6-846f-d7891f201ca6.png)

**Comment by RBEI-busmaster** [comment]
Hi ,
This is the intended behavior of signal watch.
This can be taken as an improvement later if required.
Thank you

**Comment by connectpeoplewith** [comment]
Hi RBEI,
Thank you for counting our request and devoting your valuable time!
