### ISSUE TITLE
Node Simulation Makefile will be overwritten every time on startup

### ISSUE THREAD

**Issue by mgiaco** [rbei-etas/busmaster#1107]
Pleas can you change the behavior of generating a Makefiles every time. I do need some modifications of the Makefile because i wan to use some external libs and include path for the node Simulation. 
A good way would be add a checkbox generate Makefile on startup or not. Or do you see any chance to add a potability to change the path of the Makefile template or anything else. 

So the use case is add some external libs and include path to the Makefile for the node simulation.

many thanks
cheers
mathias

**Comment by mjfwest** [comment]
@mgiaco Was this solved? I've a similar issue?

**Comment by mgiaco** [comment]
No, but i think busmaster is dead so i switched to a self written python app. Sorry
