### ISSUE TITLE
Cannot run simulated node.

### ISSUE THREAD

**Issue by ernieskaggs** [rbei-etas/busmaster#1109]
Busmaster 3.2.1
I can build a simulated node just fine, it says ".dll created successfully", but then when I try to connect the program hangs up indefinitely. 

I am using a peak adapter. I have no problems connecting unless I build a node first.

**Comment by RBEI-busmaster** [comment]
Hi, Could you please send the .cpp file and database file if associated to busmaster@in.bosch.com

**Comment by ernieskaggs** [comment]
I got it to work, I reinstalled mingw. Something must have gotten jacked up at some point.


________________________________
