### ISSUE TITLE
CANFD support for Vector VN1610

### ISSUE THREAD

**Issue by SebastianSTARITZ** [rbei-etas/busmaster#1158]
Hi, 
we're working with the Vector VN1610. Currently the device just supports CAN in Busmaster. (But is capable of measuring CANFD with Canalyzer). 

Is there a way to update the config to perform CANFD-Measurements with busmaster?

**Comment by jogo-** [comment]
See #1044

**Comment by SebastianSTARITZ** [comment]
Thx Jogo. Haven't found it through the search earlier.
