### ISSUE TITLE
Silent Uninstall of 3.2.2 not working

### ISSUE THREAD

**Issue by ostpol** [rbei-etas/busmaster#1208]
Hi,
I use PowerShell scripts to deploy Busmaster via SCCM.

I run a silent uninstall of Busmaster 3.0.0 with:
`Start-Process "C:\Program Files (x86)\BUSMASTER_v3.0.0\uninst.exe" -ArgumentList "/S" -Wait -PassThru`
Works as intended.

When I try to silently uninstall 3.2.2 with:
`Start-Process "C:\Program Files (x86)\BUSMASTER_v3.2.2\uninst.exe" -ArgumentList "/S" -Wait -PassThru`
nothing happens.

If I omit "/S" the uninstaller starts in interactive mode. Nullsoft documentation also says "/S". Any ideas on this? I need a way to uninstall the application without user interaction.

Thanks!

**Comment by Ocean1234567** [comment]
Even I am having the same issue and need it to be sorted.
Silent uninstall of Busmaster 3.2.2 doe not work .
