### ISSUE TITLE
IXXAT with VCI driver 4.0

### ISSUE THREAD

**Issue by pagit2018** [rbei-etas/busmaster#1219]
VCI drivers 4.0 have been released for compatibility with Windows10 with SecureBoot PC, but the USB-to-CAN II device is not anymore detected by BusMaster (driver selection failed).
Everything was working fine with VCI 3.0 drivers.
Any suggestions?

**Comment by IXXAT-wucherer** [comment]
Hi Pagit,

there is a new DLL wich supports IXXAT VCI V3 and V4. Also multiple controllers are supported now.
You can replace the DLL in the Busmaster installation directory and then it should work.

Issue:
https://github.com/rbei-etas/busmaster/issues/1191

Pull request here:
https://github.com/rbei-etas/busmaster/pull/1189


Best regards,
Peter

**Comment by pagit2018** [comment]
Hi Peter,

thanks so much for your so fast and usefull reply.
I can confirm that updated DLL solve the problem and BusMaster works perfectly with VCI 4.0.

Sorry for opening this without searching before...

Kind regards
Paolo

**Comment by gxurma** [comment]
where do I get that DLL from?

**Comment by IXXAT-wucherer** [comment]
[CAN_IXXAT_VCI_VCIV4_Support.zip](https://github.com/rbei-etas/busmaster/files/3155933/CAN_IXXAT_VCI_VCIV4_Support.zip)

**Comment by IXXAT-wucherer** [comment]
Hi Martin,

I uploaded it here above.

The sources you can download here:  https://github.com/rbei-etas/busmaster/pull/1189

Please feel free to ask if there are problems or questions.

Best regards,
Peter
