### ISSUE TITLE
Cannot install MinGw

### ISSUE THREAD

**Issue by toowaki** [rbei-etas/busmaster#1230]
I understand that Bustmaster need MinGw.
However, because of company security, MinGw can not be installed.

Busmaster Installation will stop at the screen which window is "Download update manifest. Downloading 'http://tdragon.net/tminst/net-manifest.txt'.".
I think that the same thing happens on PCs of several companies. 
Could you please bundle MinGw with Busmaster to avoid such problems?
![install of MinGW](https://user-images.githubusercontent.com/26063989/60757562-5aeb4100-a047-11e9-8bc9-2e49af5629cd.png)

**Comment by FrankGerlachFlex** [comment]
Did you try to delete the folder created by the installer ? I had the problem that it would not install after a partial package download. So I deleted everything and successfully re-ran the mingw installer.

**Comment by toowaki** [comment]
Thank you for your reply.

Unfortunately, I cannot download MinGw at my office due to security.  So, the problem has not been solved yet.

But, busmaster seems to work without MinGw.
I understand that MinGw is used for node simulation.
If I don't use node simulation, is it okay if I don't install MinGw?

**Comment by FrankGerlachFlex** [comment]
If you just want to monitor the CAN bus, I guess you will not need Mingw and the gcc/g++ compiler. 
But if you want to write your own Rest Bus Simulation (with emission, processing etc. of CAN messages) , you will need mingw to compile your C++ Simulation Code.

You should talk to your corporate security for an Exception. Or bring your personal laptop and do all the BUSMASTER work on that laptop.

PS: Or can you ask the IT guys to do the install for you ? Mingw and g++ and pretty much standard tools without any known security issues (except regular patches, as any complex software). g++ is widely used at Google, Facebook, Android and also major stock exchanges.

**Comment by toowaki** [comment]
I understand what MinGw is used for.
I'll consult with my IT staff to install MinGw.
