### ISSUE TITLE
Question about CAPL Scripts

### ISSUE THREAD

**Issue by hns9fe** [rbei-etas/busmaster#146]
Hello,

Can you please tell me if CAPL scripts can be converted for use in BUSMASTER.  If so, how is this accomplished and what is the resulting file?

Thanks.

**Comment by Oopsne** [comment]
I have couple of questions on this - 
1. Once the file is converted to CPP where in the BUSmaster tool/utility it can be used to run those script?
Or is it just for the purpose of using it in the backend code
2. Where can I find the code for this conversion. It will be great if a direct link is shared.
