### ISSUE TITLE
Windows 7 x64: not working

### ISSUE THREAD

**Issue by vondraussen** [rbei-etas/busmaster#183]
Will there be support for Win7 x64?

**Comment by sunilhalvi** [comment]
I'm using BUSMASTER 3.0.0, after building the project, Tool runs fine in my office PC,I copied the release folder to a PC which doesn't has visual studio, when I click on BUSMASTER.exe the tool shows the splash screen and freezes, I have tried setting compatibility to XP SP3, but didn't worked for me, kindly help to solve this

**Comment by Nit2Nat** [comment]
Please try with v3.2.2 and report

**Comment by RBEI-busmaster** [comment]
@sunilhalvi, Is BUSMASTER installed in PC which doesn't have Visual Studio?

If not, please install corresponding BUSMASTER installer as dependencies like Visual Studio redistributable will get installed along with BUSMASTER. After installation, try with release folder and let us know.
