### ISSUE TITLE
suppress errors: Invalid Max or Min value., ACTION: Value Set to default

### ISSUE THREAD

**Issue by Bosch-JakobLichterfeld** [rbei-etas/busmaster#347]
Hi there,
please suppress the error: "Invalid Max or Min value., ACTION: Value Set to default" in the log file, when converting an dbc to dbf, because it is very hard to find a "real" error if you get 1462 such errors. Busmaster calculates the values and everything is ok, no need to throw an error message.
Thanks in advance!

**Comment by Shripadk52** [comment]
I am also getting the similar warnings in the log file just wanted to know is it okay to use this file with these warnings or not
