### ISSUE TITLE
IXXAT USB-2-CAN 2 channels doesn't work

### ISSUE THREAD

**Issue by LD-SECAD** [rbei-etas/busmaster#515]
Hello everybody,

I try to use an IXXAT USB-2-CAN II interface with Busmaster.

Only channel 1 selected : work fine
Only channel 2 selected : work fine
Both Channel 1 & 2 selected : channel 1 works, but channel 2 reports an error (LED on USB-2-CAN is red)

I use latest release of VCI driver (3.5.1.3826) and Busmaster (1.8.0)

Someone could help me?

Thanks a lot!
Loïc D.

**Comment by ETAS-Nithin** [comment]
Hello Loïc,
 Unfortunately we do not have the hardware device to reproduce this issue on the subsequent releases. We hope this issue is resolved.
We would close this topic. But in case there is pending query please feel free to reach us.
