### ISSUE TITLE
"All Key Handlers" menu is checked even though the handler is disabled.

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#536]
"All Key Handlers" menu is checked even though the handler is disabled.

1. Add a key handler
2. Build and Load the cpp file
3. Enable the key handler. "All Key Handlers" menu will be checked
4. Save the configuration
5. Unload the file. "All Key Handlers" menu will still be in checked state
6. Again Build and Load the cpp file.
We can observe that "All Key Handlers" menu is checked even though the Key handler is disabled.

**Comment by RBEI-Prathiba** [comment]
Fix is available with v2.6.4
