### ISSUE TITLE
Hardware Channels are getting retained from the previous cfx when we load a configuration.

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#565]
Hardware Channels are getting retained from the previous cfx when we load a configuration.

1. Create one configuration. Add one vector channel. Save the cfx.
2. Now create one more configuration. Add both the channels of vector. Save the cfx.
3. Load the cfx created in step 1.
we can observe that the hardware channels configured in step  2 is retained.
This happens only if we two cfx are configured with same hardware.

**Comment by RBEI-Saravanan** [comment]
Fixed in v2.6.3
