### ISSUE TITLE
Regarding CAPL(.cpp) Compilation

### ISSUE THREAD

**Issue by vikijus4u** [rbei-etas/busmaster#585]
I am Vignesh , working at Caterpillar (Chennai) .

We  use Canalyzer for our project and we are trying to explore  Bus Master tool  . While I was facing some issues and tried to find out solution , I came across some issues and discussions at below  at RBEI_ETAS forum 

https://github.com/rbei-etas/busmaster/issues/218    

I am posting my queries here . If you could find convenient time , kindly provide us a solution  .  

I have installed mingw-get version 0.6.1-beta-20130910-1

Query :  

1)   I have installed Bus Master , version 1.9.0  (find the attached busmaster_version.jpg ) . 

2) I am able to transmit and recieve the messages  ,by adding . DBF file (used format converters for converting .dbc to .dbf)

3) I am selecting CAN -> Node Simulation -> Configure   (Configure Simulated Systems window opens)

4) In the Configure simulated Systems window , I am selecting a New Simulated Systems and created busmaster.sim

5) After creating busmaster.sim , I adding a new node by selecting path where capldll.dll located .

6) I select an option Add New File . I select a path ,where the converted BusMaster_test.cpp is located . After pressing open , the .cpp(the converted CAPL ) file opens .

7) The capll editing window opens (find the attached busmaster_capll_compile.jpg)

8) Now the issue is , when I try press Build and Load option , it throws some error . (find the attached capll_build_load_issue.jpg)   . I am unable to compile the file . It says "The file is either not properly built or loaded"

**Comment by RBEI-busmaster** [comment]
Hello Pramod,
BusMaster now has full support for CAN FD and is available as an add-on.
Please refer http://rbei-etas.github.io/busmaster/Add_Ons.html for the features supported
