### ISSUE TITLE
Crash Loading/Importing database file

### ISSUE THREAD

**Issue by bravo685** [rbei-etas/busmaster#595]
I was given a database file to use for a CAN application. When I open the database file the application freezes and does not recover. Looking through the help file an 'import' feature is discussed. Using ver1.9.0 I am not able to locate the menu described in the help file. The internal help suggests the Associate DB for importing a new file. Unfortunately this also freezes. I also tried to create a DB file and attempt to open it in a new project/config with the same results - application freezes.

Using Windows 8.1

The sample DB file I used (built using busmaster):
//******************************BUSMASTER Messages and signals Database ******************************//

[DATABASE_VERSION] 1.3

[PROTOCOL] CAN

[BUSMASTER_VERSION] [1.9.0]

[NUMBER_OF_MESSAGES] 1

"[START_MSG] Cluster_3,1300,8,8,1,S"
"[START_SIGNALS] NA_byte0,8,1,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte1,8,2,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte2,8,3,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte3,8,4,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte4,8,5,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte5,8,6,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte6,8,7,0,U,255,0,1,0.000000,1.000000,,"
"[START_SIGNALS] NA_byte7,8,8,0,U,255,0,1,0.000000,1.000000,,"
[END_MSG]

**Comment by RBEI-Saravanan** [comment]
We found the header of the file is not correct. Could you please check with v2.6.2. It works fine in Windows 7 and Windows 8 as well.

**Comment by RBEI-Saravanan** [comment]
The database file has the header as 
//***************************BUSMASTER Messages and signals Database ***************************//

and the expected header is :
//******************************BUSMASTER Messages and signals Database ******************************//
