### ISSUE TITLE
FlexRay : ETAS BOA hardware is not getting selected when we unplug the cable and plug it again.

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#603]
ETAS BOA hardware is not getting selected when we unplug the cable and plug it again.
1. Connect BOA hardware. Disconnect
2. Unplug the cable
3. Plug it again
4. Now select the hardware.
"Setting initialization Configuration failed" error message is displayed

**Comment by RBEI-Saravanan** [comment]
Intended behavior. To deactive hardware please select 'FlexRay->Driver Selection->Deactivate'
