### ISSUE TITLE
Unable to detect Peak can USB in v2.0.0

### ISSUE THREAD

**Issue by somavikram** [rbei-etas/busmaster#608]
Unable to detect the hardware. getting error as computer low on memory.

**Comment by frocha27** [comment]
I have issues connecting my PEAK interface.
In the menu: CAN/Driver Selection, it is not possible to select anything else but simulation.
Next to simulation menu, a tick is greyed and cannot be changed.
if try to select any othe hardware, an error message is generated in the log
Even if the device is connected (at least for the PEAK  that I am using)
Works fine on some other PC installation !!??
thanks for advice
