### ISSUE TITLE
annoying debug rebuilds with F5

### ISSUE THREAD

**Issue by PatRuelle** [rbei-etas/busmaster#616]
I had previously build v1.7 with VS2008. I had downloaded v2.0 and rebuild it with VSX2012 for both release and busmaster_debug. Both builds had an error in that UDS_Protocol.lib could not be found. Since UDS support is schedule for v2.1, I removed "$(SolutionDir)/BIN/Libs/$(OutDir)UDS_Protocol.lib" from both projects via:
link > All Options > Additional Options
When I went to debug with F5 it reported that  FLEXRAY_ETAS_BOA - busmaster_debug Win32 was out of date. I let it build it; several projects were rebuilt. This happens every time I do an F5 even though I haven't changed anything. Any ideas what is causing this? The rebuilds with every F5 is both annoying and time consuming.

**Comment by RBEI-Prathiba** [comment]
Please check with v2.6.4 and let us know if the issue is resolved
