### ISSUE TITLE
BUSMASTER v2.0.0 cannot start up on Japanese Windows PC

### ISSUE THREAD

**Issue by etas-japan-yamamoto** [rbei-etas/busmaster#629]
BUSMASTER v2.0.0 cannot start up on Japanese Windows PC if "\BUSMASTER_v2.0.0\JPN" folder exists.
If the folder was renamed BUSMASTER starts up in English mode.
At least the issue occurs on Win7 64bit Japanese machine, other types of OS are not tested.

**Comment by etas-japan-sakurai** [comment]
Just FYI -- V2.6.1 works on my Japanese version of Windows 7 64bit, without the workaround above (=removal/rename of "JPN" folder), with Japanese Language Pack which was automatically installed together.
