### ISSUE TITLE
J1939 Signal watch is not getting minimized when you minimize Busmaster

### ISSUE THREAD

**Issue by RBEI-Anita** [rbei-etas/busmaster#631]
1.Activate J1939
2.Associate J1939 database.
3.Configure Signal watch.
4.Connect. Transmit J1939 messages. Activate Signal watch window.
Minimize Busmaster. You can observe that Signal watch window is not getting minimized along with Busmaster window. Window is retained

**Comment by RBEI-Saravanan** [comment]
Issue closed with v2.6.2
