### ISSUE TITLE
The correct CAN channel is not saved when saving the BUSMASTER configuration

### ISSUE THREAD

**Issue by ghi9fe** [rbei-etas/busmaster#633]
I am using an ES581.3 and BUSMASTER2.0.0. I have set the Channel configuration up so I log CAN 2 of the ES581.3 (This is important because I am using CAN 1 with INCA). When I save the configuration and reopen BUSMASTER with this configuration, CAN 1 is always selected. This means I always have to manually select CAN 2.

Expected behaviour. The CAN channel is also saved in the configuration.

**Comment by RBEI-Saravanan** [comment]
Issue fixed and available with v2.6.3
