### ISSUE TITLE
CAN config not extracted from XML configuration

### ISSUE THREAD

**Issue by etas-lorenz** [rbei-etas/busmaster#648]
This is based on customer feedback.

It seems that the CAN device configuration is not being extracted from the xml file when the program is launched. Using the VS-COM device, I need to manually detect and configure the device each time. Several of these settings appear in the xml file (for example the com port at <Location>\\.\COM2</Location> in the config file).

**Comment by RBEI-Saravanan** [comment]
Issue fixed and available with v2.6.3
