### ISSUE TITLE
Using Perl Win32::OLE

### ISSUE THREAD

**Issue by AdamBorcsok** [rbei-etas/busmaster#667]
Im trying to use perl package in advance of test automatisation with BusMaster.
$ex->Connect(1); //command is working,
$ex->LoadAllDll(); //is also working,
$ex->EnableDisableHandlers(0); //but it is not working

GoOnline() is not working too.
So Iam not able to enbaling handlers for CAN communication.
Is there any information about it?

**Comment by RBEI-Saravanan** [comment]
COM API list updated
