### ISSUE TITLE
[COM API] StartLogging() not working

### ISSUE THREAD

**Issue by chris85s** [rbei-etas/busmaster#671]
Hi, 
i want to access BusMaster by COM API using C#.
I am able to connect via API by Connect(1);
To log the CAN trace i wanted to use the function StartLogging();
(according to the Help of BusMaster)

By executing the StartLogging() function i get an exception:
"The method or operation is not implemented".

Does anyone knows what to do?

**Comment by RBEI-Saravanan** [comment]
COM API list updated
