### ISSUE TITLE
[COM API] SendCANMSg failure

### ISSUE THREAD

**Issue by GT-Derka** [rbei-etas/busmaster#672]
I tried to use the COM Interface API:
CAN_MonitorApp.Application canMonitor = new CAN_MonitorApp.Application();
CAN_MonitorApp.CAN_MSGS sMsg = new CAN_MonitorApp.CAN_MSGS();
After filling sMsg with some data i tried to send the CAN Message:
canMonitor.SendCANMSg(sMsg);

This works fine for BUSMASTER v1.7.0, unfortunately with BUSMASTER v2.2.0 my software crashes and Visual Studio says:

Eine nicht behandelte Ausnahme des Typs "System.Runtime.InteropServices.COMException" ist in ComTest.exe aufgetreten.

Zusätzliche Informationen: Ausnahmefehler des Servers. (Ausnahme von HRESULT: 0x80010105 (RPC_E_SERVERFAULT))

I'm not sure if Issue #334 was about the same problem.

**Comment by RBEI-Saravanan** [comment]
COM API list updated
