### ISSUE TITLE
Unload and Load Simulated System does not start simulation, and sometimes crashes application.

### ISSUE THREAD

**Issue by hyei** [rbei-etas/busmaster#674]
Unload and Load Simulated System does not start simulation, and sometimes crashes application.

Busmaster v2.2

1. Select Driver -> Kvaser Light Leafv2
2. Associate Database
3. Configure Simulated Systems
4. Add Node and select a DLL
5. Build and Load or just Load 
CAN messages om Message window  observed
Unloading  at this point may cause Busmaster to crash.
6. Load The simulation does not continue/CAN messages aren't sent.(looking at message window - CAN)
Disconnecting and Reconnecting seems to resolve the issue.

**Comment by RBEI-Prathiba** [comment]
Please check with latest version v2.6.4 and let us know if it works fine

**Comment by RBEI-Prathiba** [comment]
Please check and let us know if it works fine with v2.6.4.
