### ISSUE TITLE
Node simulation starts even if handlers are disabled

### ISSUE THREAD

**Issue by GT-Derka** [rbei-etas/busmaster#681]
In this example the DLL contains a timer which periodically transmitts a CAN-Message.
After starting busmaster v2.3.0 and clicking on "Load all DLLs" the Output Window confirmes that the dll is loaded successfully. If a click at the Connect-Button follows, the transmission of the frame starts immediately although the "Start/Stop timer handler(s)" is not pressed. A click on this button activates only the button. A second click deactivates the button and stops the transmission.
Thus the timer handlers should stay deactivated when busmaster is connected (or the button needs to become activated as well).
The message handlers stay deactivated when busmaster is connected until the user clicks on "Enable Message handler(s)". This is in my eyes the correct behavior.

**Comment by RBEI-Saravanan** [comment]
This feedback is taken up and now the latest version of BusMaster contains improvements in using Node Simulation feature. With the latest changes, all buttons are removed (Example handler buttons, build and load buttons etc.) and now enables all handlers on connect. Hope this solves your issues.
