### ISSUE TITLE
Focus is not set on LIN Signal watch and Tx window when we click on it

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#683]
Focus is not set on LIN Signal watch and Tx window when we click on it

1. Signal watch : Open network statistics and signal watch window. Click on signal watch window. Window will be hidden behind network statistics window
2. Tx window : Open Tx and signal watch window. Click on Tx window.  Window will be hidden behind signal watch window

v2.3

**Comment by RBEI-Saravanan** [comment]
Behaviour of Windows modeless dialogs.
