### ISSUE TITLE
Busmaster outside visible screen

### ISSUE THREAD

**Issue by GT-Derka** [rbei-etas/busmaster#689]
To reproduce:
- Start busmaster on a laptop with additional second monitor
- Place the busmaster-window on second monitor
- close busmaster
- remove second monitor
- start busmaster

Icon of Busmaster is shown in taskbar, but Busmaster itself stays at the old position (second screen) -> not visible if only one monitor is present

My solution to get Busmaster visible again was to change the MainWnd.left-property in the windows-registry at HKEY_CURRENT_USER\Software\RBEI-ETAS\BUSMASTER_v2.3.0\MainWnd

**Comment by RBEI-Saravanan** [comment]
Issue fixed and available with v2.6.3
