### ISSUE TITLE
J1939 Simulated system is getting retained when we create a new configuration.

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#712]
J1939 Simulated system is getting retained when we create a new configuration.

1. Activate J1939.
2. Create a simulated system. Add a node. 
3. Deactivate J1939.
4. Save the configuration.
5. Close and relaunch the application.
6. Create a new configuration.
7. Activate J1939.
8. Open J1939 Simulated system window.
The simulated system settings is retained from previous configuration.

v2.4

**Comment by RBEI-Saravanan** [comment]
Fixed
