### ISSUE TITLE
Losing bits on 10 bits signal

### ISSUE THREAD

**Issue by Juegadamas** [rbei-etas/busmaster#719]
I added a message (DLC=4) with 3 signals to my database.
a two bit signal starting byte index 0 and bit No 6. 
and the other two signals with index 1 and 3, bit No 0 and lenght 10 bits.
Byte order motorolla.

I trace signals individually:
2bitsignal= 0;
10bitsignal1 = 198
10bitsignal2 = 265
then the message should be:
C1 98 02 65

when i send the message busmaster shows:
C0 98 01 65

![10signalbit](https://cloud.githubusercontent.com/assets/8023575/3493042/ab682a64-05b3-11e4-90e1-0678d456a34b.jpg)

SO: Windows 7 64 bits

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
