### ISSUE TITLE
Error during build release configuration

### ISSUE THREAD

**Issue by mazurekw** [rbei-etas/busmaster#726]
Hi,

I tried to compile the current bus master source environment of Microsoft Visual Studio 2012 Express and Microsoft Visual Studio 2012 Professional. Despite the fact that everything is set up however it is described in the document development_environment.pdf, the compilation result is 1676 warnings and 1 error. Many of these warnings are because of outdated compiler settings, type conversion problems, unsafe function usage.
 It is not a problem, but the error description is: 
"error MSB3073: The command ""F:\busmaster-master_3express\busmaster-master\Sources\BIN/Release\BusEmulation.exe" /RegServer
:VCEnd" exited with code -2147024891.   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets". 

Have you any suggestions on how to solve the problem with the above error?

Any advice would be greatly appreciated.

**Comment by kragod** [comment]
Hi, and about the error LNK1108 cannot open truetrue.obj. Can you help me?
