### ISSUE TITLE
LIN frame type(Master, Slave) radio buttons are getting disabled whenever we switch between Hex and Dec numeric format

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#739]
LIN frame type(Master, Slave) radio buttons in Tx window are getting disabled whenever we switch between Hex and Dec numeric format.

1. Open LIN Tx window. Master and Slave radio buttons will be enabled.
2. Change the numeric format(Hex or Dec)
Now the radio buttons gets disabled.

v2.5

**Comment by RBEI-Saravanan** [comment]
Added proper checks.
