### ISSUE TITLE
Database Editor: Issues regarding signed signals

### ISSUE THREAD

**Issue by GT-Derka** [rbei-etas/busmaster#741]
In DatabaseEditor - CAN I created a message and added a 32-bit-signal of int-type, Scale Factor=1, Offset=0.

1. The textboxes are too small to show the whole number.
2. When creating the signal the calculated Min and Max Values are correct.
3. Back in DatabaseEditor-Window the (positive) Max Val is correctly shown as 7FFFFFFF(hex). But the Min Val is shown as 80000000(hex), which is indeed correct, but confuses the user. I would prefer a signed decimal-view. In hex-view the Min Val seems to be larger than Max Val.
4. Edit Signal... openes Signal Details again and shows wrongly 1.968.526.677 as Max Value.
(New Desc.... still shows the correct number)
5. A thousands-separator would make the numbers readable to human eyes ;-)
6. Scale Factor does not influence Min and Max Val but it should

**Comment by RBEI-Saravanan** [comment]
Fixed
