### ISSUE TITLE
Application is minimized as soon as we launch it.

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#743]
Application is minimized as soon as we launch it.

1. Minimize application.
2. Close the application by right clicking on the icon in the taskbar and selecting close window option.
3. Now launch the application.
Application will be minimized and we cannot maximize it by clicking on the icon in the task bar.

v2.5

**Comment by RBEI-Saravanan** [comment]
Issue fixed and available with v2.6.3
