### ISSUE TITLE
Node Simulation Big Endian

### ISSUE THREAD

**Issue by vondraussen** [rbei-etas/busmaster#750]
Is there a bug within Node Simulation with big endian?
When i increment one 16Bit Signal it will overwrite to the high nibble of the following 16Bit Signal.

Both Signals are 16Bit big endian. When I test to increment in the static "send message" it will work just fine.

The test database is namend haltech. In the generated file "haltech_Unions.h" I saw that theres something strange in the generated struct:

```c
struct
	{
	    unsigned int                  :  8 ; // <<-- what is this for?
	    unsigned int RPM              : 16 ;
	    unsigned int Throttle_V       : 16 ;
	    unsigned int                  : 24 ;

	} __attribute__((__packed__));
```
If helpful, I can provide my test files.
I tested this with 2.3.0 and 2.5.0

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
