### ISSUE TITLE
Signal packing problem in simulation

### ISSUE THREAD

**Issue by nostar** [rbei-etas/busmaster#756]
I created a small test simulation & database to describe this problem. I created a dbf with 6 Motorola unsigned ints in msg01.  The first 3 in order are 8 bit, then 2 16 bit, then one more 8 bit.  The problem is that busmaster simulated node refuses to send a 16bit signal at byte index 4 (which would be 3 and 4), instead it transmit the signal data on byte 4 and byte 5, so it overwrites half of the following signal.  The next 16 bit signal is also shifted over by 1 byte, and finally, the last signal in the message doesnt show up in the message at all.  In the simulation, Sig04 in msg01 has a padding byte added to the struct which shouldn't be there.  Even if I comment it out though, the signal is still packed into the message incorrectly.  It will pack correctly if move Sig04 up to the first, second, or third location, but it always jumps over byte location 4.  In the simulation I send:

Msg01_tx.m_sWhichBit.Sig04 = 0x1234;

and the result is: 
00 00 00 00 34 12 00 00

It should be:
00 00 00 34 12 00 00 00

I am aware of the byte order issue #750 but this is something else.

I created msg02 full of 8 bytes, no problems there.  I can send a zip file of the small (25KB) simulation if anyone wants it.

byteorder.dbf:
//******************************BUSMASTER Messages and signals Database ******************************//

[DATABASE_VERSION] 1.3

[PROTOCOL] CAN

[BUSMASTER_VERSION] [2.5.0]

[NUMBER_OF_MESSAGES] 2

[START_MSG] msg01,258,8,6,1,S
[START_SIGNALS] Sig01,8,1,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] Sig02,8,2,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] Sig03,8,3,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] Sig04,16,5,0,U,65535,0,0,0.000000,1.000000,,
[START_SIGNALS] Sig05,16,7,0,U,65535,0,0,0.000000,1.000000,,
[START_SIGNALS] Sig06,8,8,0,U,255,0,0,0.000000,1.000000,,
[END_MSG]

[START_MSG] msg02,259,8,8,1,S
[START_SIGNALS] sig0,8,1,0,U,85,0,0,0.000000,1.000000,,
[START_SIGNALS] sig1,8,2,0,U,85,0,0,0.000000,1.000000,,
[START_SIGNALS] sig2,8,3,0,U,85,0,0,0.000000,1.000000,,
[START_SIGNALS] sig3,8,4,0,U,85,0,0,0.000000,1.000000,,
[START_SIGNALS] sig4,8,5,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] sig5,8,6,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] sig6,8,7,0,U,255,0,0,0.000000,1.000000,,
[START_SIGNALS] sig7,8,8,0,U,255,0,0,0.000000,1.000000,,
[END_MSG]

byteorder_Unions.h
/* This is an ALWAYS automatically generated file based on the database ... */
/*It is recommended to change the database directly. If you want to prevent overwritten header files, make a copy of it and ensure you include the intended version in your node simulation.*/

#pragma once
#pragma pack(pop,8)

#ifndef MESSAGENAME_msg01
#define MESSAGENAME_msg01
typedef union 
{
	unsigned char      m_aucData[64];
	unsigned short int m_auwData[4];
	unsigned long  int m_aulData[2];

	struct
	{
	    unsigned int Sig01            :  8 ;
	    unsigned int Sig02            :  8 ;
	    unsigned int Sig03            :  8 ;
	    unsigned int                  :  8 ;//This shouldn't be here
	    unsigned int Sig04            : 16 ;
	    unsigned int Sig05            : 16 ;
	    unsigned int Sig06            :  8 ;

	} __attribute__((__packed__));
}msg01_;
typedef struct 
{
	unsigned int  m_unMsgID       ;
	unsigned char m_ucEXTENDED    ;
	unsigned char m_ucRTR         ;
	unsigned char m_ucDLC         ;
	unsigned char m_ucChannel	;
	msg01_        m_sWhichBit     ;

	UINT m_ulTimeStamp;
	bool		     m_bCANFD        ;

} msg01;
#endif /* MESSAGENAME_msg01 */

#ifndef MESSAGENAME_msg02
#define MESSAGENAME_msg02
typedef union 
{
	unsigned char      m_aucData[64];
	unsigned short int m_auwData[4];
	unsigned long  int m_aulData[2];

	struct
	{
	    unsigned int sig0             :  8 ;
	    unsigned int sig1             :  8 ;
	    unsigned int sig2             :  8 ;
	    unsigned int sig3             :  8 ;
	    unsigned int sig4             :  8 ;
	    unsigned int sig5             :  8 ;
	    unsigned int sig6             :  8 ;
	    unsigned int sig7             :  8 ;

	} __attribute__((__packed__));
}msg02_;
typedef struct 
{
	unsigned int  m_unMsgID       ;
	unsigned char m_ucEXTENDED    ;
	unsigned char m_ucRTR         ;
	unsigned char m_ucDLC         ;
	unsigned char m_ucChannel	;
	msg02_        m_sWhichBit     ;

	UINT m_ulTimeStamp;
	bool		     m_bCANFD        ;

} msg02;
#endif /* MESSAGENAME_msg02 */

1.cpp (my node)
/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.5.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>

#include "C:\Users\cz0n9v\Documents\busmaster\configs\byteorder\byteorder_Unions_fixed.h"
/* End BUSMASTER include header */

/* Start BUSMASTER global variable */
msg01 Msg01_tx = {0x102, 0, 0, 8, 1};
/* End BUSMASTER global variable */

/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_timer_100ms_100( );
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnBus_Disconnect();
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnTimer_timer_100ms_100 */
void OnTimer_timer_100ms_100( )
{
	Msg01_tx.m_sWhichBit.Sig04 = 0x1234;
	SendMsg(*((STCAN_MSG *)&Msg01_tx));
}/* End BUSMASTER generated function - OnTimer_timer_100ms_100 */
/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
StartTimer("timer_100ms", 100);
}/* End BUSMASTER generated function - OnBus_Connect */
/* Start BUSMASTER generated function - OnBus_Disconnect */
void OnBus_Disconnect()
{
StopTimer("timer_100ms");
}/* End BUSMASTER generated function - OnBus_Disconnect */

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
