### ISSUE TITLE
Channel selection/configuration not correctly saved.

### ISSUE THREAD

**Issue by etas-lorenz** [rbei-etas/busmaster#757]
This is based on customer feedback:

I wanted to report the following misconduct which greatly reduces the usability. 
I have 2 or more ETAS BOA devices connected. e.g. ES523 and ES593-D. 
The Channel Selection dialog offers me eight channel at 
ETAS: // ETH / ES523: 9900045 / CAN: 1 
ETAS: // ETH / ES523: 9900045 / CAN: 2 
ETAS: // ETH / ES523: 9900045 / CAN: 3 
ETAS: // ETH / ES523: 9900045 / CAN: 4 
ETAS: // ETH / ES593_D: 2202375 / CAN: 1 
ETAS: // ETH / ES593_D: 2202375 / CAN: 2 
ETAS: // ETH / ES593_D: 2202375 / CAN: 3 
ETAS: // ETH / ES593_D: 2202375 / CAN: 4 
I select 
ETAS: // ETH / ES593_D: 2202375/CAN: 2 
and call channel configuration. 
After I have tested the configuration I save it. 
After a restart of the bus master and load the saved configuration
ETAS: // ETH / ES523: 9900045/CAN: 1 
is selected !?

**Comment by RBEI-Saravanan** [comment]
Issue fixed and available with v2.6.3
