### ISSUE TITLE
"An unsupported operation was attempted" error message is poping up when we double click on the signal in CAN Tx window

### ISSUE THREAD

**Issue by RBEI-Pramod** [rbei-etas/busmaster#763]
"An unsupported operation was attempted" error message is popping up when we double click on the signal in CAN Tx window.

1. Associate a DB.
2. Open CAN Tx window and add a message to Tx list.
3. Now double click on the message signal.
"An unsupported operation was attempted" error message is displayed.

Expected result : Signal details window should open.

v2.6

**Comment by RBEI-Saravanan** [comment]
Fixed and updated in v2.6.1
