### ISSUE TITLE
Enable/Disable interpret button looks like activated mode when unpressed "override mode" button.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#778]
Steps-
1.Activate override mode" button in tool bar
2.Click on interpret button
3.Now deactivate override button
4.check the interpret button now.

Expected Behaviour - interpret button must be displayed as like disable mode.
Actual behaviour -  it displayed as activated mode.

Note: This issue can be produced only with a default configuration.

**Comment by RBEI-Saravanan** [comment]
Issue closed with v2.6.2
