### ISSUE TITLE
[Tree View of Simulated Systems window] - simulated system file under "LIN Bus" is not replaced by the new one

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#780]
GUI Check -  Tree View of Simulated Systems window
1. When the simulated system which is already under "LIN Bus" has to be replaced by the new one , and the dll s under it are in loaded state. 

Expected behavior -A dialog box should indicate the user that the dlls under the selected system are loaded. Unload it first and try again.
Actual Behavior - A dialog box appeared saying "file already exist.Do you want to replace it".Then on replacing it is not replaced with fresh sim file.

**Comment by RBEI-Saravanan** [comment]
Same .sim file is not allowed to be created.
Issue closed with v2.6.2
