### ISSUE TITLE
Node Simulation(j1939) - Signal re-declaration error occurs during build even if the signal names are unique

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#782]
j1939-Node Simulation error:(Busmaster 2.6.1)
1.Associate j1939 dbf file .
2.Go to node simulator,Create new node and build cpp file  for it.
The below error occurred during build even if the signals are unique.
Error:  Redeclaration of 'unsigned int  < anonymous int > :: < anonymous structure >

**Comment by RBEI-Saravanan** [comment]
Issue closed with v2.6.2
