### ISSUE TITLE
Open the .c file created for J1939

### ISSUE THREAD

**Issue by FairozeNakhath** [rbei-etas/busmaster#791]
I wrote a CAPL program containing J1939 diagnostic messages such as DM1 - DM16. I converted the .can file to .cpp file using Busmaster's format Converter. I also converted j1939 dbc to dbf and associated it inside J1939->Database->Associate.

But after creating a node under J1939->Node Simulation->Configure . When trying to add the .cpp file , the system shows the below error message. 

"File is not created for J1939. Please open the .c file created for J1939"

Please tell if there is any other converter available with respect to j1939.

**Comment by RBEI-Saravanan** [comment]
CAPL to CPP converter is available only for CAN as of now
