### ISSUE TITLE
CAN Bus repeater and filtering on vehicle

### ISSUE THREAD

**Issue by shenkera** [rbei-etas/busmaster#793]
Hi,

Do you know if the BUSMASTER tool has the ability to read CAN signals via one hardware interface, and repeat them out to another hardware interface(while filtering out some messages) ?

Thanks in advance!

**Comment by RBEI-Prathiba** [comment]
Hi,
You can use 'Node Simulation' feature in BusMaster with the following steps:
1. Configure 'Message Handlers' in Node Simulation editor, for the messages to be repeated. Message Handler will get executed on reception of the respective message
2. Received message details will be available in parameter RxMsg, configure the m_ucChannel (to point to new hardware) 
3. Use SendMsg(..) API to send the message to different channel connected to new hardware

For more details, please refer help section 'CAN->API Reference'
