### ISSUE TITLE
Signal description with Chinese characters can not show in signal watch window.

### ISSUE THREAD

**Issue by dreampet** [rbei-etas/busmaster#794]
The Chinese characters description can show correctly in the “Database Editor” window, but when add this signal in to the "Signal Watch" window, it is show in messy code.
![messy](https://cloud.githubusercontent.com/assets/12544313/7748056/a00bf7e6-fff3-11e4-8176-3666d4feb398.png)

**Comment by dreampet** [comment]
By the way, the Chinese characters description it is also show in messy code in the "Message Window".
![Uploading Messy2.png…]()

**Comment by RBEI-Prathiba** [comment]
Currently BusMaster NLS support includes only Japanese and German language strings partially.
