### ISSUE TITLE
LDF File

### ISSUE THREAD

**Issue by happysmile09** [rbei-etas/busmaster#800]
I have some confusion, would you please help me?
I understand LIN protocol, but when i read the LDF file, i see definition for Signal from source to receiver. And frame defined the source, but no receiver. 
What is the meaning of signal?
Thanks very much!

**Comment by RBEI-Prathiba** [comment]
In LDF file, Frame will have signals mapped, receivers of the frames are the receivers of signals mapped to the respective frame. For more details, please load the .ldf file in BUSMASTER 'LDF Editor' and refer 'LIN Network View' to see the Publisher (Transmitter) and Subscribers (Receivers) of the Frames and Signals.

To invoke 'LDF Editor', please refer help section 'LIN->LIN Database Editor'
