### ISSUE TITLE
Pannel support Busmaster

### ISSUE THREAD

**Issue by dinguluer** [rbei-etas/busmaster#809]
Hi,

Do busmaster supports for Pannel build ?

I saw this link :---
https://github.com/rbei-etas/busmaster/issues/84

If not, can i create a pannel in QT creator & send/receive CAN bus event using busmaster server ?

If it is possible, can you guide me to the documentation to access busmaster server ?

Regards,
Dinesh

**Comment by RBEI-Saravanan** [comment]
Thank you for the interest.
Panels is not yet supported. Yes, that a good idea to use QT creator and use BusMaster server for send and receive.

Please refer to the help file on the below topics for APIs.
CAN ==> COM Interface

**Comment by RBEI-busmaster** [comment]
Hello,
BusMaster supports Instruments add-on to create GUI and use it for communication. 
Please refer http://rbei-etas.github.io/busmaster/Add_Ons.html for more details

**Comment by yijoung** [comment]
So it means that Instruments add-on is not free and it's paid?
