### ISSUE TITLE
Support for new ES581.4

### ISSUE THREAD

**Issue by psyklopz** [rbei-etas/busmaster#813]
ETAS no longer sells the ES581.3 and has replaced it with the ES581.4.  Busmaster doesn't seem to support this adapter in any way.  Please add support for this new adapter.

**Comment by RBEI-Prathiba** [comment]
ES581.4 can be accessed using 'CAN->Driver Selection->ETAS BOA', if you have Boa framework (v2.0 and above) installed.

**Comment by Pdeokar** [comment]
Having issues with Driver Selection when using ES581.4 and Busmaster 2.6.3. It gives 'Driver Selection Failed". Working on Windows 7. 
I installed USB driver for ES581.4 through HSP (V10.10.0) and also upgraded firmware on to V3.0.0. But when try to select driver => CAN\Driver Selection\ETAS BOA from the main menu, it gives me 'Driver Selection Failed' .

I also tried changing BusMaster compatibility mode to Windows XP too, didn't help.

**Comment by psyklopz** [comment]
@Pdeokar You need to install the BOA Framework, available here:
http://www.etas.com/en/downloadcenter/18102.php

Make sure to restart afterwards.
It's not included on the CD that comes with the ES581.4.

**Comment by Pdeokar** [comment]
It worked! Thanks

**Comment by ranjandhingra923** [comment]
i have installed BOA framework. i can successfully select DRIVER as ETAS BOA, can further assign CAN1 to channel 1, but after that when i connect , NO signals are shown in the CAN window. Can you assist as what can be the cause ?
