### ISSUE TITLE
Problem on negative data visualization

### ISSUE THREAD

**Issue by mauro-ongaro** [rbei-etas/busmaster#816]
In CONFIGURE TRANSMISSION MESSAGES wiew I saw a problem in visualization.

![busmaster](https://cloud.githubusercontent.com/assets/1662164/8854971/f587fcd8-3162-11e5-8ebc-6ea8414cf555.JPG)

I saw also that in the MESSAGE WINDOW - CAN view that a 32bit signed int is not displayed correctly when negative.

Best regards
Mauro

**Comment by mauro-ongaro** [comment]
An image about the problem MESSAGE WINDOW - CAN view that a 32bit signed int is not displayed correctly when negative.
![busmaster2](https://cloud.githubusercontent.com/assets/1662164/8874895/72a4584e-3215-11e5-9f12-542157c7894e.JPG)

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
