### ISSUE TITLE
Problems while loading Fibex File 3.1.0

### ISSUE THREAD

**Issue by RoSchCo** [rbei-etas/busmaster#822]
Hello!
While loading a Fibex File 3.1.0 Busmaster crashes. Other Fibex File with the same version can be loaded w/o any problem. Is there any known problem behind?
Thx in advance!

**Comment by RBEI-Saravanan** [comment]
Could you check with v2.6.3 ?

**Comment by RoSchCo** [comment]
Hello!

For the moment it looks like "normal active". :-)

What are the main changes of ....3?

Many thx,
Robert!



Von:    RBEI-Saravanan <notifications@github.com>
An:     rbei-etas/busmaster <busmaster@noreply.github.com>, 
Kopie:  RoSchCo <robert.scheruebl@continental-corporation.com>
Datum:  10.08.2015 11:28
Betreff:        Re: [busmaster] Problems while loading Fibex File 3.1.0 
(#822)



Could you check with v2.6.3 ?
