### ISSUE TITLE
Conversion of DBC file

### ISSUE THREAD

**Issue by RoSchCo** [rbei-etas/busmaster#838]
Hello!
We convert a DBC File to DBF and it is done w/o failures. But if we want to have a look on the converted database no messages are shown even if inside the dbc messages are available.
Thx!

**Comment by RBEI-Prathiba** [comment]
Please let us know the version used and send the .dbc file to BUSMASTER@in.bosch.com

**Comment by RoSchCo** [comment]
Hello!

I opened the database with the CANdb++ Editor and saved it w/o changing 
anything. Now I am also able to convert it inside Busmaster. 

So I guess it was really a problem of the dbc file.

Many thx nevertheless.

Bye,
Robert!



Von:    RBEI-Prathiba <notifications@github.com>
An:     rbei-etas/busmaster <busmaster@noreply.github.com>, 
Kopie:  RoSchCo <robert.scheruebl@continental-corporation.com>
Datum:  14.09.2015 08:09
Betreff:        Re: [busmaster] Conversion of DBC file (#838)



Please let us know the version used and send the .dbc file to 
BUSMASTER@in.bosch.com
