### ISSUE TITLE
Wrong Value displayed in "Edit  Desciptor" dialog box for CAN.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#849]
Value is not retained in "Edit  Desciptor " dialog box for CAN.

Version - [ Busmaster_2_6_3  ]
Follow the below steps.
1.open Datasbase editor [CAN] and create new message.
2.Create new signal of type int .
3.Create new description with value of 14.
4.click on Edit description.
5.Previous value is not retained.It is shown 4.

**Comment by RBEI-Prathiba** [comment]
Fix is available with v2.6.4
