### ISSUE TITLE
Database file(.dbf) for CAN is deleted automaticallly.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#855]
Database file(.dbf) for CAN is deleted automaticallly.
Follow the below steps to reproduce the issue.
 [ Version -Busmaster_2.6.3 ]
1.Create a new Database for CAN .
2.Create a New Mesasge.
3.Close the database window.
4.Click  on "Save" in the dialog box.
5.Open the same database again and Close the database window.

The created database(.dbf )file is deleted from the location.

**Comment by RBEI-Prathiba** [comment]
Fix is available with v2.6.4
