### ISSUE TITLE
Bushmaster crashes when selection IntrepidCS NeoVI as the driver. 

### ISSUE THREAD

**Issue by houghtonbrad** [rbei-etas/busmaster#869]
I'be successfully used bushmaster with the Valuecan3 in the past without problem. I've recently purchased a new valuecan3 device and installed the drivers that came along with it. Now when try to set up a bus master session and select The IntrepidCS neoVI the program crashes. I've uninstalled and reinstalled both bushmaster and the valuecan3 device. I've looked around and found that this has happened before, but cannot find any fixes. I've tried on versions 2.6.3 and 2.6.4. Any feedback on the matter what be greatly appreciated!

**Comment by RBEI-Prathiba** [comment]
Duplicate to #817, hence closing the issue.
#817 is used for further tracking and updates.
