### ISSUE TITLE
DBF files do not support Float32/64 data types

### ISSUE THREAD

**Issue by jarheck** [rbei-etas/busmaster#874]
When creating an new DBF file or converting a DBC file I noticed there is not an option for choosing an IEEE floating point number.

**Comment by RBEI-Prathiba** [comment]
Currently BusMaster supports data types only for Raw values. Physical values will be calculated based on the offset, factor and Signal Length etc taken from database.

**Comment by jarheck** [comment]
Yes but there is no way to calculate the physical value of a Floating point number (CANalyzer, etc support this option to view physical values) as this is an allowed datatype in a DBC file. It would be a nice improvement in the future to support this data type.

**Comment by TheOtherMarcus** [comment]
This should be reopened. Busmaster doesn't display physical float values correctly when DBF is converted from DBC.
