### ISSUE TITLE
Application got Crashed when used invalid .dbf file.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#875]
Follow below steps to reproduce :
1.Create invalid .dbf file.
2.Launch Busmaster.Open the invalid  .dbf file in Busmaster.
3.Go to Can->Database->New
4.DatasbaseCAN Editor will be opened.Right click on the tree node.
Application got crashed.

**Comment by RBEI-busmaster** [comment]
Fix already available
