### ISSUE TITLE
error in network statistics

### ISSUE THREAD

**Issue by thomasyyf** [rbei-etas/busmaster#883]
Hallo,
I’m trying to use Busmaster to calculate error frames in CAN bus. However I didn’t see any error in Network statistics, even there is error message shown in Message window. Can any one guide me how to calculate errors?

**Comment by RBEI-Prathiba** [comment]
Hi,
Please let us know the version of BUSMASTER and hardware used.

**Comment by thomasyyf** [comment]
Hallo,
I’m using ES511.1, Busmaster V2.6.4.

Mit freundlichen Grüßen/Best regards
Yuanfeng Yao

**Comment by RBEI-busmaster** [comment]
Could you please check with latest version 3.1.0 and let us know if it works.
