### ISSUE TITLE
Signal descriptor Value is not updated as per hex/decimal selection.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#904]
Busmaster Version- 2.6.4
Follow the below steps .
1.Open Database editor window of CAN/J1939.Create Signal descriptor in any message.
2.Change the hex/Decimal value from tool bar .

Signal descriptor Value  is not updated as per hex/decimal selection.

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
