### ISSUE TITLE
m_ucMsgID variable  is not displayed correct mesasge id when used in Nodesimulation.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#910]
Used below code to identify message id in message handler Function .It is displayed the same id in Trace on receiving of every messages. (Busmaster-2.6.4)

Trace("messageid-%d",RxMsg.m_ucMsgID);

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
