### ISSUE TITLE
Application got Crashed when master request  sent using DBmessage from node simulation- LIN.

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#911]
Follow the below steps to reproduce the issue.

1.Import any LDf file and enable master mode.Select Driver selection.
2. In Lin-Tx window,Configure a dbmessage as master .
3.In Node simulation,Configure the same db message as slave in preconnect .

 dbmessage sMsgDB;
  sMsgDB.m_ucMsgTyp = 1; // Slave Response
  // Send the message
SendMsg(*((STLIN_MSG *)&sMsgDB));

4.Connect LIN from toolbar..
Application got crashed.

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
