### ISSUE TITLE
Error in Replay:Invalid message found further messages cannot be replayed

### ISSUE THREAD

**Issue by Sanchez029** [rbei-etas/busmaster#921]
Hi¡¡ I am starting with Busmaster and I found this problem when i try to replay a .log file that I generate with Busmaster, what could I do to avoid this error? 

Thanks

**Comment by Mazighe** [comment]
Try to replay from another file it will be easy

**Comment by edriver** [comment]
Hi,
Seams that replay fails when there is a zero byte length message is in your logfile.
E.g. 16:10:18:2755 Rx 1 0x080 s 0

After replacing this entry with
16:10:18:2755 Rx 1 0x080 s 1 00
Replay is working

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
