### ISSUE TITLE
Message window interprets values wrong

### ISSUE THREAD

**Issue by schnurksel** [rbei-etas/busmaster#940]
The Message window interprets the message values wrong while at the same moment the same value is interpreted inside the signal watch window right.
Example: The Raw value is 0x3E0 at the signal window and the message window.
The signal window interprets this value right as as -32 while the message window shows 992.
See attached image.
![busmaster](https://cloud.githubusercontent.com/assets/6735897/15553818/34045010-22c1-11e6-9aa4-324e78521686.jpg)
The value is a 10 Bit signed value with offset 0. The message windows shows it as an unsigned value (1024 - 32 = 992).

**Comment by RBEI-VENKAT** [comment]
We are working on this issue along with the similar issues ( #719 , #750, #756 )

**Comment by RBEI-busmaster** [comment]
Fixed the issue. Updated with v3.0.0
