### ISSUE TITLE
The file "mfc120.dll" is missing as startup

### ISSUE THREAD

**Issue by PPSXIN** [rbei-etas/busmaster#950]
Hello,
I have installed v3.0.0, but unfortunately, while I tried to start up the software, the warning is propelled, I have attached the warning capture FYR. BTW, my PC OS is win7 X64.
![capture](https://cloud.githubusercontent.com/assets/20082167/16574771/06a7b968-42b5-11e6-8bd0-09e6adedc406.JPG)

**Comment by RBEI-Prathiba** [comment]
BUSMASTER v3.0.0 requires Visual Studio 2013 Redistributable installation.
For installation, please refer the link https://github.com/rbei-etas/busmaster/wiki/Visual-Studio-2013-Redistributable

**Comment by Gardneia113** [comment]
![pic](https://cloud.githubusercontent.com/assets/20450759/16828988/8ccc3154-49c7-11e6-8e9b-9d12c8b2d8a2.png)


I have installed Visual Studio 2013 Redistributable,but the interval of sending message, is the twice of my setting.

**Comment by RBEI-busmaster** [comment]
Issue fixed with v3.1.0
