### ISSUE TITLE
Not able to traverse through the filter list using arrow keys

### ISSUE THREAD

**Issue by RBEI-Srinibas** [rbei-etas/busmaster#954]
steps to reproduce the issue : [ver-3.0.0]
1. open Busmaster application 
2. open filter configuration [Either for CAN or LIN] 
3. Add 3 filters 
4.click on the first filter 
5.Press the down arrow key 
[Second filter gets selected for renaming and clicking anywhere else in the window is showing a pop-up for "name already exists". 
The filter name is empty and we can not delete it.

**Comment by RBEI-busmaster** [comment]
Fixed
