### ISSUE TITLE
Two's complements in Signal Information

### ISSUE THREAD

**Issue by Secmick** [rbei-etas/busmaster#960]
Hi,

I try to create in .dbf file Signal information with Two's complements signal.
Description of Signal:
Type : int
Byte Index : 2
Start Bit : 0
Length : 16 bits
Factor : -0.008750
Byte Order : Motorola

Send HEX Message over CAN: 
Scenario 1:
00 02 3B 00 00 00 00 00 
Expected: -4.996
Result: -4.996
See "Correct_Message.PNG"

Scenario 2:
00 FD C3 00 00 00 00 00 
Expected: 5
Result: -567.426
See "Incorrect_Message.PNG"

Can you please help with this issue.

Thanks

![correct_message](https://cloud.githubusercontent.com/assets/20534775/16945385/7153f9fe-4dad-11e6-801c-ab0591f5c28e.PNG)
![incorrect_message](https://cloud.githubusercontent.com/assets/20534775/16945386/71572c50-4dad-11e6-8bde-30e8cf13c0fa.PNG)

**Comment by RBEI-busmaster** [comment]
Big Endian/Motorola signal issues are addressed in the latest BusMaster v3.0.0. Please check with the latest version.
