### ISSUE TITLE
Can't save database in Test Automation module (Busmaster v3.0.0)

### ISSUE THREAD

**Issue by partychowski** [rbei-etas/busmaster#970]
Reproduction Steps:
1.Navigate to Test Automation -Editor.
2.Create new Test Suite
3.In Details window try to add database in DataBase Path.

Actual Result:
3. Path to database is not visible, after validate test suite - No Database File is Included message appears.

**Comment by RBEI-busmaster** [comment]
Issue fixed with the latest version
