### ISSUE TITLE
Panel for Node Simulation needed

### ISSUE THREAD

**Issue by PeterSchmutt** [rbei-etas/busmaster#975]
During Node Simulation, we need a panel/GUI to interact with the user (e.g. an Automotive Dasboard). We know such a feature from Vector CANalyzer pro. 
- Can such a feature be implemented in further versions?
- Is it already possible to attach for example a Visual Basic GUI by some SW interface?

**Comment by RBEI-busmaster** [comment]
Duplicate to #84 and Panel support will be tracked using the same. Hence closing the issue.
