### ISSUE TITLE
Decoding of CAN value tables in message window is broken in V3.0

### ISSUE THREAD

**Issue by Pilt2013** [rbei-etas/busmaster#979]
Using an associated database (converted from dbc to dbf), V3.0 no longer displays the decoded value from a value table in the CAN database

Examples (see FastChg):

V2.6.3
![image](https://cloud.githubusercontent.com/assets/5130674/18245592/fc5947d6-735d-11e6-9717-2e5622128f59.png)

V3.0
![image](https://cloud.githubusercontent.com/assets/5130674/18245628/37c224fa-735e-11e6-80fb-f45fd1da1644.png)

Unless im missing a setting to turn this on?

**Comment by RBEI-busmaster** [comment]
Closing the issue as it is similar to #951.
Issue #951 can be used for tracking.
