### ISSUE TITLE
Message window interpretation signal for state rather than value

### ISSUE THREAD

**Issue by AutologicAU** [rbei-etas/busmaster#984]
I have a message where there are multiple signals one or more of those signals represent a change in state which is determined by the raw value in the signal.
In the expanded replay window or the signal interpretation window I want to be able to see the state in addition to the value.
for example;
I have a message 0x335 where byte index 0 which is 8 bits long which the signal signifies if the brakes are applied or not.
if the value is 0 the brakes are off
if the value is 16 the brakes are applied

I would like to see the state either brakes off or brakes applied in the interpretation in addition to the actual raw and physical numerical values.
 
How can I do this?....thankyou

**Comment by RBEI-busmaster** [comment]
Closing the issue as it is similar to #951.
Issue #951 can be used for tracking.
