### ISSUE TITLE
Possible to add a close source plugin?

### ISSUE THREAD

**Issue by grandangelo** [rbei-etas/busmaster#989]
Good morning,

I'm working for a test bench designer company. We have developed internally a CAN driver using a CAN port natively available on a uPC used in our devices.

I've been using Busmaster in my previous job and found it really useful. I would like to propose to my boss the use of this tool, but open sourcing any code unluckily does not seem an option.

Thus my question: is it possible to add support for a CAN hardware device without releasing the source code?

Many thanks for any answer or suggestion.
Andrea

**Comment by ETAS-Nithin** [comment]
Hi Andrea,

Greetings! The source code distribution depends on how the component (in this case, your custom HW support) integration & distribution is made. Perhaps you could write to us at BUSMASTER@in.bosch.com to understand the plan. Thanks
