### ISSUE TITLE
Missing mfc120.dll in BUSMASTER v3.0.0

### ISSUE THREAD

**Issue by piyushk93** [rbei-etas/busmaster#994]
System configuration:
Windows 7.
system type: 64 bit os
![error](https://cloud.githubusercontent.com/assets/24263569/20740476/5bf35f28-b6e9-11e6-8b0e-d504df512dbb.PNG)

While starting BUSMASTER v3.0.0 it gives error that the program can't start because mfc120.dll is missing from your computer, try reinstalling the program to fix this problem.
after re-installation the same error occurs.

**Comment by RBEI-busmaster** [comment]
Hi,

BUSMASTER v3.0.0 requires Visual Studio 2013 Redistributable installation.
For installation, please refer the link https://github.com/rbei-etas/busmaster/wiki/Visual-Studio-2013-Redistributable.

Closing the issue, As it is similar to #950. #950 will be used for tracking.

**Comment by piyushk93** [comment]
Thanks for your solution, it's working.
